[BUG] iOS build failure with JWPlayerKit 4.20.0
jwplayer/jwplayer-react-native pull request #91
Opened 2024-10-14 17:44 UTC by Jmilham21

### What does this Pull Request do?
- Remove soon to be deprecated callback
- Only use a specific version of the iOS SDK.

### Why is this Pull Request needed?
- Prepare for next iOS release with breaking deprecations
- Ensure the version in the podspec is tested and viable with this wrapper

### Are there any points in the code the reviewer needs to double check?
- no

### Are there any Pull Requests open in other repos which need to be merged with this?
- no

#### Addresses Issue(s):

[GitHub Issue](https://github.com/jwplayer/jwplayer-react-native/issues/89)

2024-10-14 17:45 UTC, Jmilham21 commented
For anyone waiting for this, you will need to ensure your podfile.lock is updated to only use the specific version as stated in the podspec here.

2024-11-15 19:14 UTC, chriszs commented
Thanks!

2024-11-26 21:15 UTC, AmitaiB requested changes

2024-11-26 22:47 UTC, Jmilham21 commented on Example/ios/Podfile.lock
> +  - google-cast-sdk (4.8.3):
This was accidental. We weren't being specific with our versioning in the RNJWPlayer.podspec so it updated without my consent. Good catch

2024-11-27 16:14 UTC, merged